"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f7+wr$q2$vu(0wskmy$n8vr+-rp2cs)h_u47yg+v)j6$cxd%$+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['192.168.123.89', '127.0.0.1', 'yangxiaodi.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
	# 'DjangoUeditor',
	'ckeditor',
	'ckeditor_uploader',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'blog.apps.BlogConfig',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	# 'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')]
		,
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				# 'django.core.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db1.sqlite3'),
	}
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATETIME_FORMAT = 'Y-m-d H:i:s'

DATE_FORMAT = 'Y-m-d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, './blog/static/')


# upload folder
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, './blog/media')
CKEDITOR_UPLOAD_PATH = 'upload/'
CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_ALLOW_NONIMAGE_FILES = False  # 不允许非图片文件上传，默认为True
CKEDITOR_BROWSE_SHOW_DIRS = True  # 在编辑器里浏览上传的图片时，图片会以路径分组，日期排序
CKEDITOR_RESTRICT_BY_USER = True  # 限制用户浏览图片的权限，只能浏览自己上传的图片，图片会传到以用户名命名的文件夹下，超级管理员依旧可以看所有图片

CKEDITOR_CONFIGS = {
	'default': {
		'language': 'zh-cn',
		'skin': 'moono-lisa',
		# 'skin': 'office2013',
		'toolbar_Basic': [
			['Source', '-', 'Bold', 'Italic']
		],
		'toolbar_YourCustomToolbarConfig': [
			{'name': 'document', 'items': ['Source', '-', 'Save', 'Preview', '-', 'Undo', 'Redo']},
			{'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord']},
			{'name': 'insert',
			 'items': ['Image', 'Table', 'HorizontalRule', 'Smiley']},
			{'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
			{'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
			{'name': 'paragraph',
			 'items': ['-', 'Blockquote', '-',
			           'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
			'/',
			{'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
			{'name': 'colors', 'items': ['TextColor', 'BGColor']},
			{'name': 'basicstyles',
			 'items': ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat', 'NumberedList', 'BulletedList',
			           '-', 'Outdent', 'Indent', 'CodeSnippet']},
		],
		'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
		'tabSpaces': 4,
		'extraPlugins': ','.join([
			'uploadimage',  # the upload image feature
			'div',
			'autolink',
			'autoembed',
			'embedsemantic',
			'autogrow',
			'widget',
			'lineutils',
			'clipboard',
			'dialog',
			'dialogui',
			'elementspath',
			'codesnippet',
			'prism',
		]),
	}
}

